src/main/java/org/savanah/web/AntecedentJudiciaireBean.java
package org.savanah.web;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

import org.primefaces.event.TransferEvent;
import org.primefaces.model.DualListModel;
import org.savanah.domain.AntecedentJudiciaireEntity;
import org.savanah.domain.CitoyenEntity;
import org.savanah.domain.InfractionEntity;
import org.savanah.service.AntecedentJudiciaireService;
import org.savanah.service.CitoyenService;
import org.savanah.service.InfractionService;
import org.savanah.service.security.SecurityWrapper;
import org.savanah.web.generic.GenericLazyDataModel;
import org.savanah.web.util.MessageFactory;

@Named("antecedentJudiciaireBean")
@ViewScoped
public class AntecedentJudiciaireBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(AntecedentJudiciaireBean.class.getName());
    
    private GenericLazyDataModel<AntecedentJudiciaireEntity> lazyModel;
    
    private AntecedentJudiciaireEntity antecedentJudiciaire;
    
    @Inject
    private AntecedentJudiciaireService antecedentJudiciaireService;
    
    @Inject
    private InfractionService infractionService;
    
    @Inject
    private CitoyenService citoyenService;
    
    private DualListModel<InfractionEntity> infractions;
    private List<String> transferedInfractionIDs;
    private List<String> removedInfractionIDs;
    
    private List<CitoyenEntity> availableCitoyenList;
    
    public void prepareNewAntecedentJudiciaire() {
        reset();
        this.antecedentJudiciaire = new AntecedentJudiciaireEntity();
        // set any default values now, if you need
        // Example: this.antecedentJudiciaire.setAnything("test");
    }

    public GenericLazyDataModel<AntecedentJudiciaireEntity> getLazyModel() {
        if (this.lazyModel == null) {
            this.lazyModel = new GenericLazyDataModel<>(antecedentJudiciaireService);
        }
        return this.lazyModel;
    }
    
    public String persist() {

        if (antecedentJudiciaire.getId() == null && !isPermitted("antecedentJudiciaire:create")) {
            return "accessDenied";
        } else if (antecedentJudiciaire.getId() != null && !isPermitted(antecedentJudiciaire, "antecedentJudiciaire:update")) {
            return "accessDenied";
        }
        
        String message;
        
        try {
            
            if (antecedentJudiciaire.getId() != null) {
                antecedentJudiciaire = antecedentJudiciaireService.update(antecedentJudiciaire);
                message = "message_successfully_updated";
            } else {
                antecedentJudiciaire = antecedentJudiciaireService.save(antecedentJudiciaire);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        
        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        
        return null;
    }
    
    public String delete() {
        
        if (!isPermitted(antecedentJudiciaire, "antecedentJudiciaire:delete")) {
            return "accessDenied";
        }
        
        String message;
        
        try {
            antecedentJudiciaireService.delete(antecedentJudiciaire);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));
        
        return null;
    }
    
    public void onDialogOpen(AntecedentJudiciaireEntity antecedentJudiciaire) {
        reset();
        this.antecedentJudiciaire = antecedentJudiciaire;
    }
    
    public void reset() {
        antecedentJudiciaire = null;

        infractions = null;
        transferedInfractionIDs = null;
        removedInfractionIDs = null;
        
        availableCitoyenList = null;
        
    }

    // Get a List of all citoyen
    public List<CitoyenEntity> getAvailableCitoyen() {
        if (this.availableCitoyenList == null) {
            this.availableCitoyenList = citoyenService.findAvailableCitoyen(this.antecedentJudiciaire);
        }
        return this.availableCitoyenList;
    }
    
    // Update citoyen of the current antecedentJudiciaire
    public void updateCitoyen(CitoyenEntity citoyen) {
        this.antecedentJudiciaire.setCitoyen(citoyen);
        // Maybe we just created and assigned a new citoyen. So reset the availableCitoyenList.
        availableCitoyenList = null;
    }
    
    public DualListModel<InfractionEntity> getInfractions() {
        return infractions;
    }

    public void setInfractions(DualListModel<InfractionEntity> infractions) {
        this.infractions = infractions;
    }
    
    public List<InfractionEntity> getFullInfractionsList() {
        List<InfractionEntity> allList = new ArrayList<>();
        allList.addAll(infractions.getSource());
        allList.addAll(infractions.getTarget());
        return allList;
    }
    
    public void onInfractionsDialog(AntecedentJudiciaireEntity antecedentJudiciaire) {
        // Prepare the infraction PickList
        this.antecedentJudiciaire = antecedentJudiciaire;
        List<InfractionEntity> selectedInfractionsFromDB = infractionService
                .findInfractionsByAntecedentJudiciaire(this.antecedentJudiciaire);
        List<InfractionEntity> availableInfractionsFromDB = infractionService
                .findAvailableInfractions(this.antecedentJudiciaire);
        this.infractions = new DualListModel<>(availableInfractionsFromDB, selectedInfractionsFromDB);
        
        transferedInfractionIDs = new ArrayList<>();
        removedInfractionIDs = new ArrayList<>();
    }
    
    public void onInfractionsPickListTransfer(TransferEvent event) {
        // If a infraction is transferred within the PickList, we just transfer it in this
        // bean scope. We do not change anything it the database, yet.
        for (Object item : event.getItems()) {
            String id = ((InfractionEntity) item).getId().toString();
            if (event.isAdd()) {
                transferedInfractionIDs.add(id);
                removedInfractionIDs.remove(id);
            } else if (event.isRemove()) {
                removedInfractionIDs.add(id);
                transferedInfractionIDs.remove(id);
            }
        }
        
    }
    
    public void updateInfraction(InfractionEntity infraction) {
        // If a new infraction is created, we persist it to the database,
        // but we do not assign it to this antecedentJudiciaire in the database, yet.
        infractions.getTarget().add(infraction);
        transferedInfractionIDs.add(infraction.getId().toString());
    }
    
    public void onInfractionsSubmit() {
        // Now we save the changed of the PickList to the database.
        try {
            List<InfractionEntity> selectedInfractionsFromDB = infractionService
                    .findInfractionsByAntecedentJudiciaire(this.antecedentJudiciaire);
            List<InfractionEntity> availableInfractionsFromDB = infractionService
                    .findAvailableInfractions(this.antecedentJudiciaire);
            
            for (InfractionEntity infraction : selectedInfractionsFromDB) {
                if (removedInfractionIDs.contains(infraction.getId().toString())) {
                    infraction.setAntecedentJudiciaire(null);
                    infractionService.update(infraction);
                }
            }
    
            for (InfractionEntity infraction : availableInfractionsFromDB) {
                if (transferedInfractionIDs.contains(infraction.getId().toString())) {
                    infraction.setAntecedentJudiciaire(antecedentJudiciaire);
                    infractionService.update(infraction);
                }
            }
            
            FacesMessage facesMessage = MessageFactory.getMessage(
                    "message_changes_saved");
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            
            reset();

        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            FacesMessage facesMessage = MessageFactory.getMessage(
                    "message_optimistic_locking_exception");
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            FacesMessage facesMessage = MessageFactory.getMessage(
                    "message_picklist_save_exception");

src/main/java/org/savanah/web/InfractionBean.java
package org.savanah.web;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;
import org.primefaces.event.FlowEvent;
import org.savanah.domain.AntecedentJudiciaireEntity;
import org.savanah.domain.CitoyenEntity;

import org.savanah.domain.InfractionEntity;
import org.savanah.service.AntecedentJudiciaireService;
import org.savanah.service.CitoyenService;
import org.savanah.service.InfractionService;
import org.savanah.service.security.SecurityWrapper;
import org.savanah.web.generic.GenericLazyDataModel;
import org.savanah.web.util.MessageFactory;

@Named("infractionBean")
@ViewScoped
public class InfractionBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(InfractionBean.class.getName());

    private GenericLazyDataModel<InfractionEntity> lazyModel;

    private InfractionEntity infraction;
    private CitoyenEntity citoyen;
    private AntecedentJudiciaireEntity antecedent;

    @Inject
    private InfractionService infractionService;
    @Inject
    private CitoyenService citoyenService;
    @Inject
    private AntecedentJudiciaireService antecedentJudiciaireService;
    private boolean skip;

    public void prepareNewInfraction() {
        reset();
        this.infraction = new InfractionEntity();
        // set any default values now, if you need
        // Example: this.infraction.setAnything("test");
    }

    public GenericLazyDataModel<InfractionEntity> getLazyModel() {
        if (this.lazyModel == null) {
            this.lazyModel = new GenericLazyDataModel<>(infractionService);
        }
        return this.lazyModel;
    }

    public String persist() {
        if (infraction.getId() == null && !isPermitted("infraction:create")) {
            return "accessDenied";
        } else if (infraction.getId() != null && !isPermitted(infraction, "infraction:update")) {
            return "accessDenied";
        }

        String message;
        try {
            if (infraction.getId() != null) {
                infraction = infractionService.update(infraction);
                message = "message_successfully_updated";
            } else {
                CitoyenEntity citoyenEntity = new CitoyenEntity();
//                citoyenEntity.setAdresse("adresse");
//                citoyenEntity.setNom("xis xis");
                AntecedentJudiciaireEntity antecedentJudiciaireEntity = new AntecedentJudiciaireEntity();
//                antecedentJudiciaireEntity.setDate(new Date());
//                antecedentJudiciaireEntity.setDescription("hakakkajjk");
                antecedentJudiciaireEntity.setCitoyen(citoyenEntity);
                infraction.setAntecedentJudiciaire(antecedentJudiciaireEntity);
                infraction = infractionService.save(infraction);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);

        return null;
    }

    public String delete() {

        if (!isPermitted(infraction, "infraction:delete")) {
            return "accessDenied";
        }

        String message;

        try {
            infractionService.delete(infraction);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));

        return null;
    }

    public void onDialogOpen(InfractionEntity infraction) {
        reset();
        this.infraction = infraction;
    }

    public void reset() {
        infraction = null;

    }

    public InfractionEntity getInfraction() {
        if (this.infraction == null) {
            prepareNewInfraction();
        }
        return this.infraction;
    }

    public void setInfraction(InfractionEntity infraction) {
        this.infraction = infraction;
    }

    public boolean isPermitted(String permission) {
        return SecurityWrapper.isPermitted(permission);
    }

    public boolean isPermitted(InfractionEntity infraction, String permission) {

        return SecurityWrapper.isPermitted(permission);

    }

    public List<InfractionEntity> getAllInfraction() {

        return infractionService.findAllInfractionEntities();
    }

    public boolean isSkip() {
        return skip;
    }

    public void setSkip(boolean skip) {
        this.skip = skip;
    }

    public String onFlowProcess(FlowEvent event) {
        if (skip) {
            skip = false;   //reset in case user goes back
            return "confirm";
        } else {
            return event.getNewStep();
        }
    }

    public CitoyenEntity getCitoyen() {
        if (this.citoyen == null) {
            reset();
            this.citoyen = new CitoyenEntity();
        }
        return this.citoyen;
    }

    public AntecedentJudiciaireEntity getAntecedent() {
        if (this.antecedent == null) {
            reset();
            this.antecedent = new AntecedentJudiciaireEntity();
        }
        return this.antecedent;
    }

    public void setCitoyen(CitoyenEntity citoyen) {
        this.citoyen = citoyen;
    }

    public void setAntecedent(AntecedentJudiciaireEntity antecedent) {
        this.antecedent = antecedent;
    }

}

src/main/webapp/pages/infraction/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
    <ui:composition template="/WEB-INF/template.xhtml">
        <ui:define name="content">

            <h:form prependId="false" id="infractionDataForm" onkeypress="if (even
                            t.keyCode ==
                            13
                            ) {
                        return false;
                    }">

                <p:dataTable id="infractionTable" value="#{infractionBean.allInfraction}" var="infraction" resizableColumns="true" paginator="true"
                             paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true" lazy="false"
                             paginatorPosition="bottom" widgetVar="infractionTable" emptyMessage="#{messages.label_no_records_found}"
                             reflow="true">

                    <p:column headerText="Noms" filterBy="#{infraction.antecedentJudiciaire.citoyen.nom}">
                        <h:outputText value="#{infraction.antecedentJudiciaire.citoyen.nom} #{infraction.antecedentJudiciaire.citoyen.postNom} #{infraction.antecedentJudiciaire.citoyen.prenom}" />
                    </p:column>


                    <p:column  headerText="Infraction"  filterBy="#{infraction.nom}">

                        <h:outputText value="#{infraction.nom}" />
                    </p:column>

                    <p:column headerText="Peine" >
                        <h:outputText value="#{infraction.peine}" />
                    </p:column>
                    <p:column headerText="Date" filterBy="#{infraction.antecedentJudiciaire.date}">
                        <h:outputText value="#{infraction.antecedentJudiciaire.date}"><f:convertDateTime dateStyle="short" type="date" pattern="dd/MM/YYYY"></f:convertDateTime></h:outputText>
                    </p:column>

                    <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">

                        <p:commandButton icon="ui-icon-zoomin" update=":viewInfractionDialog" oncomplete="PF('viewInfractionDialogWidget').show()" title="#{messages.label_view}">
                            <f:setPropertyActionListener value="#{infraction}" target="#{infractionBean.infraction}" />
                        </p:commandButton>
                        <p:commandButton icon="fa fa-print" >

                        </p:commandButton>
                        <p:commandButton icon="ui-icon-pencil" update=":editInfractionDialog"
                                         resetValues="true" rendered="#{infractionBean.isPermitted(infraction, 'infraction:update')}"
                                         action="#{infractionBean.onDialogOpen(infraction)}"
                                         oncomplete="PF('editInfractionDialogWidget').show()"
                                         title="#{messages.label_edit}" >
                        </p:commandButton>

                        <p:commandButton icon="ui-icon-close" rendered="#{infractionBean.isPermitted(infraction, 'infraction:delete')}"
                                         oncomplete="PF('deleteInfractionDialogWidget').show()"
                                         title="#{messages.label_delete}" >
                            <f:setPropertyActionListener value="#{infraction}"
                                                         target="#{infractionBean.infraction}" />
                        </p:commandButton>

                    </p:column>
                    <f:facet name="footer" >

                        <p:commandButton value="#{messages.create_new_infraction}" icon="ui-icon-plusthick" action="#{infractionBean.prepareNewInfraction()}"
                                         resetValues="true" update=":editInfractionDialog" oncomplete="PF('editInfractionDialogWidget').show()"
                                         rendered="#{infractionBean.isPermitted('infraction:create')}" style="float:left"  />

                        <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" rendered="false" />
                        <p:columnToggler datasource="infractionTable" trigger="toggler" rendered="false"/>
                    </f:facet>
                </p:dataTable>

            </h:form>

            <p:confirmDialog id="deleteInfractionDialog" widgetVar="deleteInfractionDialogWidget"
                             rendered="#{infractionBean.isPermitted(infractionBean.infraction, 'infraction:delete')}" header="#{messages.label_confirm_deletion}"
                             severity="alarm">
                <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
                <p:outputPanel>
                    <h:form>
                        <div style="text-align: center; margin:10px">
                            <p:commandButton value="#{messages.label_yes}" action="#{infractionBean.delete}" update=":infractionDataForm :growlForm:growl" oncomplete="PF('deleteInfractionDialogWidget').hide()" />
                            <p:commandButton value="#{messages.label_no}" onclick="PF('deleteInfractionDialogWidget').hide()" type="button" />
                        </div>
                    </h:form>
                </p:outputPanel>
            </p:confirmDialog>

            <p:dialog dynamic="true" id="editInfractionDialog" header="#{messages.label_infraction_caption}"
                      modal="true" widgetVar="editInfractionDialogWidget" maximizable="true">
                <p:ajax event="close" listener="#{infractionBean.reset}"/>
                <h:form id="editInfractionForm" >
                    <p:outputPanel id="infractionEditPanel">
                        <ui:include src="/pages/infraction/infractionEditInclude.xhtml"/>
                        <div style="text-align: center; margin:10px">
                            <p:commandButton value="#{messages.label_save}"
                                             icon="ui-icon-disk" action="#{infractionBean.persist}"
                                             update=":editInfractionForm:infractionEditPanel :infractionDataForm :growlForm:growl"
                                             oncomplete="if(!args.validationFailed) PF('editInfractionDialogWidget').hide()" />
                            <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('editInfractionDialogWidget').hide()" type="button" />
                        </div>
                    </p:outputPanel>
                </h:form>
            </p:dialog>

            <p:dialog dynamic="true" id="viewInfractionDialog" header="#{messages.label_infraction_caption}" modal="true" widgetVar="viewInfractionDialogWidget" maximizable="true">
                <p:ajax event="close" listener="#{infractionBean.reset}" />
                <h:form id="viewInfractionForm">
                    <ui:include src="/pages/infraction/infractionViewInclude.xhtml"/>
                    <div style="text-align: center; margin:10px">
                        <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('viewInfractionDialogWidget').hide()" type="button" />
                    </div>
                </h:form>
            </p:dialog>

        </ui:define>
    </ui:composition>
</html>

src/main/webapp/pages/infraction/infraction.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">

    <h:form prependId="false" id="infractionDataForm" onkeypress="if (event.keyCode == 13) {return false; }">

        <p:dataTable id="infractionTable" value="#{infractionBean.lazyModel}" var="infraction" resizableColumns="true" paginator="true"
                paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true" lazy="true"
                paginatorPosition="bottom" widgetVar="infractionTable" emptyMessage="#{messages.label_no_records_found}"
                reflow="true">
        
          <f:facet name="header" >

              <p:commandButton value="#{messages.create_new_infraction}" icon="ui-icon-plusthick" action="#{infractionBean.prepareNewInfraction()}"
                      resetValues="true" update=":editInfractionDialog" oncomplete="PF('editInfractionDialogWidget').show()"
                      rendered="#{infractionBean.isPermitted('infraction:create')}" style="float:left" />
              
              <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
              <p:columnToggler datasource="infractionTable" trigger="toggler" />
          </f:facet>
          
          <p:column  headerText="#{messages.field_label_infraction_nom}" sortBy="#{infraction.nom}" filterBy="#{infraction.nom}">
            <f:facet name="filter">
                <p:inputText id="nomFilter"
                        onkeypress="if (event.keyCode == 13) {PF('infractionTable').filter(); updateNomFilter(); return false; }" >
                    <p:remoteCommand name="updateNomFilter" update="infractionTable:nomFilter" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{infraction.nom}" />
          </p:column>

          <p:column  headerText="#{messages.field_label_infraction_peine}" sortBy="#{infraction.peine}" filterBy="#{infraction.peine}">
            <f:facet name="filter">
                <p:inputText id="peineFilter"
                        onkeypress="if (event.keyCode == 13) {PF('infractionTable').filter(); updatePeineFilter(); return false; }" >
                    <p:remoteCommand name="updatePeineFilter" update="infractionTable:peineFilter" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{infraction.peine}" />
          </p:column>

          <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">
            
            <p:commandButton icon="ui-icon-zoomin" update=":viewInfractionDialog" oncomplete="PF('viewInfractionDialogWidget').show()" title="#{messages.label_view}">
              <f:setPropertyActionListener value="#{infraction}" target="#{infractionBean.infraction}" />
            </p:commandButton>

            <p:commandButton icon="ui-icon-pencil" update=":editInfractionDialog"
                resetValues="true" rendered="#{infractionBean.isPermitted(infraction, 'infraction:update')}"
                action="#{infractionBean.onDialogOpen(infraction)}"
                oncomplete="PF('editInfractionDialogWidget').show()"
                title="#{messages.label_edit}" >
            </p:commandButton>

            <p:commandButton icon="ui-icon-close" rendered="#{infractionBean.isPermitted(infraction, 'infraction:delete')}"
                oncomplete="PF('deleteInfractionDialogWidget').show()"
                title="#{messages.label_delete}" >
                <f:setPropertyActionListener value="#{infraction}"
                    target="#{infractionBean.infraction}" />
            </p:commandButton>
    
          </p:column>
          
        </p:dataTable>
        
    </h:form>

    <p:confirmDialog id="deleteInfractionDialog" widgetVar="deleteInfractionDialogWidget"
        rendered="#{infractionBean.isPermitted(infractionBean.infraction, 'infraction:delete')}" header="#{messages.label_confirm_deletion}"
        severity="alarm">
        <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
        <p:outputPanel>
          <h:form>
            <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_yes}" action="#{infractionBean.delete}" update=":infractionDataForm :growlForm:growl" oncomplete="PF('deleteInfractionDialogWidget').hide()" />
              <p:commandButton value="#{messages.label_no}" onclick="PF('deleteInfractionDialogWidget').hide()" type="button" />
            </div>
          </h:form>
        </p:outputPanel>
    </p:confirmDialog>
    
    <p:dialog dynamic="true" id="editInfractionDialog" header="#{messages.label_infraction_caption}"
            modal="true" widgetVar="editInfractionDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{infractionBean.reset}"/>
        <h:form id="editInfractionForm" >
            <p:outputPanel id="infractionEditPanel">
                <ui:include src="/pages/infraction/infractionEditInclude.xhtml"/>
                <div style="text-align: center; margin:10px">
                    <p:commandButton value="#{messages.label_save}"
                            icon="ui-icon-disk" action="#{infractionBean.persist}"
                            update=":editInfractionForm:infractionEditPanel :infractionDataForm :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('editInfractionDialogWidget').hide()" />
                    <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('editInfractionDialogWidget').hide()" type="button" />
                </div>
            </p:outputPanel>
        </h:form>
    </p:dialog>
    
    <p:dialog dynamic="true" id="viewInfractionDialog" header="#{messages.label_infraction_caption}" modal="true" widgetVar="viewInfractionDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{infractionBean.reset}" />
        <h:form id="viewInfractionForm">
          <ui:include src="/pages/infraction/infractionViewInclude.xhtml"/>
          <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('viewInfractionDialogWidget').hide()" type="button" />
          </div>
        </h:form>
    </p:dialog>
    
  </ui:define>
</ui:composition>
</html>